### ISSUE TITLE
Generate JavaDoc for all classes at once

### ISSUE THREAD

**Issue by saeidzebardast** [setial/intellij-javadocs#19]
Thank you for this useful plugin. Is there anyway to generate JavaDoc for all classes at once?!

**Comment by macelano** [comment]
this would be very useful.  is there a unit test that you can share that I could start with?

**Comment by TSergey** [comment]
Implemented in https://github.com/setial/intellij-javadocs/commit/d1717bae561af3f396486fc0abd3a84ee5ed52ee

Will be available since 1.0.11 release

**Comment by macelano** [comment]
Excellent I look forward to trying this feature out. thank you
