### ISSUE TITLE
Inline javadocs

### ISSUE THREAD

**Issue by maurezen** [setial/intellij-javadocs#22]
While writing javadoc for constructor or getter/setter methods one often needs to comment parameters or return values which should have javadoc identical to one of a certain field, e.g. a constructor initializing several class fields by setting them to the provided values. In a similar fashion, delegates could benefit from method javadoc inlining.

Right now one has to use @see links, which may be undesirable.

An option to inline javadoc text of an existing entity would be helpful.

**Comment by TSergey** [comment]
Hi @maurezen. It's not very clear for me what you mean.

Could you please provide some examples of what you need?

**Comment by maurezen** [comment]
@TSergey sorry, it's hard to comment on whatever problem I had 2 years ago. For me it's not an issue anymore.
