### ISSUE TITLE
Unable to generate in IDEA 14

### ISSUE THREAD

**Issue by davidsowerby** [setial/intellij-javadocs#36]
I've looked at issue #34 for an answer, but so far I have been unable to use this plugin at all.

I am using Ultimate v14.0.3 and I've just installed the plugin and restarted (twice, just to be sure!)

- I have tried invoking generation using the keys [described](https://github.com/setial/intellij-javadocs/wiki), and get no response at all. 
- There is no key conflict on either combination. 
- Javadoc Sync Plugin 10 shows in 'Plugins' and is enabled
- The generate popup dialog ("alt + insert") does not contain any reference to Javadoc
- I'm running IDEA on Ubuntu Linux

**Comment by TSergey** [comment]
You mentioned about "Javadoc Sync Plugin 10" but it seems that another plugin.
Could you please make sure you have installed "JavaDoc" plugin.
I 've attached screenshot of plugin section with selected plugin
![plugin](https://cloud.githubusercontent.com/assets/1842437/6429009/e9b83eb6-bf86-11e4-9217-791eb452cbba.jpg)

**Comment by davidsowerby** [comment]
My apologies, somehow I was confused between the two plugins - yours is working fine.
