### ISSUE TITLE
"RuntimeException: Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document."

### ISSUE THREAD

**Issue by mattalexx** [setial/intellij-javadocs#40]
![Image of Yaktocat](http://i.imgur.com/Bksgjts.png)

**Comment by nyxee** [comment]
I'm having the same error too. 
This tool is extremely useful to me.

Is there an alternative please.
I saw a mention of [Fix Doc] somewhere (??)

**Comment by TSergey** [comment]
Hi guys. I will try to fix this issue during the next week.
The difficulties is that I can not reproduce that, so I am fixing this on my guess.

**Comment by TSergey** [comment]
Can you give me some hints on the issue:
does it happen all the time on the same action?
what action do you perform when you see exception?
what action was just before you get error?

**Comment by TSergey** [comment]
This should be fixed in https://github.com/setial/intellij-javadocs/releases/tag/intellij-javadocs-2.0.1
