### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by Mistic92** [setial/intellij-javadocs#47]
Hi. Is it possible to add custom tags like author with date to template? 
For example when I edit or write new method I push shortcut and whole javadoc with author tag is generated or author tag is updated with my data and date.

**Comment by TSergey** [comment]
Hi.
You can find some example on wiki page: https://github.com/setial/intellij-javadocs/wiki/Javadoc-templates

For example you can edit template and setup the following code there:

`@author YourName created on ${.now?string["MM.dd.yyyy"]}`
