### ISSUE TITLE
How to config the time @date?

### ISSUE THREAD

**Issue by kings1990** [setial/intellij-javadocs#48]
I want to record the time when my java class or my method? how can i realize it?

**Comment by TSergey** [comment]
You can find documentation here:
https://github.com/setial/intellij-javadocs/wiki/Javadoc-templates

Basically you can use the following template:
`/**\n`
` * The type ${name}.\n`
` * \n`
` * @date ${.now?string["MM.dd.yyyy"]} \n`
` */`
