### ISSUE TITLE
How to change Getters/Setters generated javaDoc?

### ISSUE THREAD

**Issue by claudineij** [setial/intellij-javadocs#49]
When I use Alt+Insert in a getter and generate the javaDoc, I get this:

    /**
     * Gets foo.
     *
     * @return the foo
    */

But, I want to change this to something like 

    /**
     * @return o valor de foo
    */
Where I modify this? I tried Settings > Other Settings > Javadoc > Templates, but I cant find where to change there to modify only getters/setters javaDocs.

**Comment by TSergey** [comment]
Hi.
Currently it is not clear which settings are stands for.
But in future I will probably improve this.

So, regarding your question:
please go to the Settings->Other Settings->Javadoc->Templates
In "Method level" settings first line is for getters and and the second line is for setters.
