### ISSUE TITLE
Retrieve the date from the velocity template

### ISSUE THREAD

**Issue by PierreAdam** [setial/intellij-javadocs#52]
Hi,

I'm currently trying to retrieve the date from the template for the javadoc. I've been trying to use the object [DateTool](https://velocity.apache.org/tools/devel/javadoc/org/apache/velocity/tools/generic/DateTool.html) but it doesn't seems to work. It even seems that the DateTool class is not accessible.

What i want to do is generate a javadoc as follow : 
``` java
/**
* My function
* 
* @param p description
* @since 16.02
* @return description
**/
public String myFunction(String p) {...}
```
The ```@since``` is the year and the month (so 16.02).

I was wondering if i missed something or if there is something to modify in the plugin.

Thanks

**Comment by TSergey** [comment]
Hi.
The thing is that template engine in plugin is freemarker:
http://freemarker.incubator.apache.org/docs/ref_builtins.html

So, example of javadoc template with dates you can find in docs:
https://github.com/setial/intellij-javadocs/wiki/Javadoc-templates
