### ISSUE TITLE
Settings edition on IntelliJ 2016.1.1

### ISSUE THREAD

**Issue by PierreAdam** [setial/intellij-javadocs#55]
Hi,

Since I updated IntelliJ to the version 2016.1.1 I'm unable to find the Javadoc settings menu in my settings under the section Other Settings.

The plugin is still functional, but I can't change the configuration anymore.
Has the menu moved or is it a bug?

**Comment by hbprotoss** [comment]
same here

**Comment by zhaoqin102** [comment]
not here

**Comment by ranzou06** [comment]
same here!

**Comment by zhaoqin102** [comment]
[https://img3.doubanio.com/view/photo/photo/public/p2352290310.jpg](url)
but not here!

**Comment by zhaoqin102** [comment]
[https://github.com/zhaoqin102/profile/blob/master/1534.tmp.png](url)
but not here!

**Comment by zhaoqin102** [comment]
![1534 tmp](https://cloud.githubusercontent.com/assets/11658078/15279648/515a14fc-1b59-11e6-8e77-9a4283ece8d8.png)
but not here

**Comment by hbprotoss** [comment]
@zhaoqin102 

> I'm unable to find the Javadoc settings menu in my settings under the section **Other Settings**.

**Comment by zhaoqin102** [comment]
@hbprotoss I don't understand what you mean

**Comment by hbprotoss** [comment]
@zhaoqin102 I mean JavaDoc settings menu does not appear in this section :)
![image](https://cloud.githubusercontent.com/assets/2310905/15285606/c5da70b6-1b8a-11e6-9a3d-b441f2f5b5aa.png)

**Comment by hbprotoss** [comment]
@zhaoqin102 I have to manually edit the xml configuration file to change settings of the plugin

**Comment by PierreAdam** [comment]
Bug still present on version 2016.1.2 of Intellij Idea.

**Comment by ranzou06** [comment]
![image](https://cloud.githubusercontent.com/assets/4295849/15300565/a192ada0-1b7f-11e6-969e-cb57d3eed61c.png)

**Comment by Black3v3r** [comment]
Same problem here. @hbprotoss , you said that you edited the templates in the file directly. Where is this file ?

**Comment by hbprotoss** [comment]
@Black3v3r On OSX, it is located in `~/Library/Preferences/IntelliJIdea2016.1/options/intellij-javadocs.xml`

**Comment by jmengelle** [comment]
Using IDEA 2016.1.3 and have the same problem. 

Thanx to @hbprotoss , i found to xml file. 
Under windows : 
    <userDir>/IntelliJIdea2016.1\config\options/intellij-javadocs.xml

Personnaly, i added the option to generate comment on private method. 

      <VISIBILITIES>
        <VISIBILITY>PROTECTED</VISIBILITY>
        <VISIBILITY>DEFAULT</VISIBILITY>
        <VISIBILITY>PUBLIC</VISIBILITY>
        <VISIBILITY>PRIVATE</VISIBILITY>
      </VISIBILITIES>

**Comment by mozhuwanjieDEV** [comment]
@PierreAdam 
I have such a problem.
I'm unable to find the Javadoc settings menu in my settings under the section Other Settings.

ps:
IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_05-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

JavaDoc version: 3.1.0

**Comment by ranzou06** [comment]
i got it fixed.

https://github.com/ranzou06/intellij-javadocs/blob/master/intellijPluginJavadoc.zip

**Comment by hbprotoss** [comment]
@ranzou06 template not loaded currectly
![image](https://cloud.githubusercontent.com/assets/2310905/16217417/d9656c4e-37a5-11e6-94ee-dd08994caecc.png)
![image](https://cloud.githubusercontent.com/assets/2310905/16217424/e1e6c2d2-37a5-11e6-971e-961fed072b33.png)

**Comment by mozhuwanjieDEV** [comment]
@ranzou06 

Cannot save my own configuration.

Unable to save plugin settings

The plugin com.github.setial failed to save settings and has been disabled. Please restart IntelliJ IDEA

**Comment by ranzou06** [comment]
i have only fixed the configuration file, i will check that later.

**Comment by ranzou06** [comment]
JetBrains gays has change a fill things on the persistence api, i have made a fix, hope it will for you all.

https://github.com/ranzou06/intellij-javadocs/blob/master/intellij-javadocs.zip?raw=true

**Comment by hbprotoss** [comment]
@ranzou06 It works, thx

**Comment by dliszewski** [comment]
What I should do with jars from your file @ranzou06 ?

**Comment by ranzou06** [comment]
@dliszewski  grab the last one and install it from the plugins configuration screen on the IDE.

**Comment by amwk** [comment]
@ranzou06 What have you changed ?

**Comment by ranzou06** [comment]
@amwk from the version 2016.1.1 some deprecated settings have been removed from intellij, i have just updated the plugins settings and fixed some details about the new persistence API, basically i have just used a singleton.

**Comment by sudi7402** [comment]
thx

**Comment by techbrew-mc** [comment]
Confirming @ranzou06's fix (#issuecomment-228579013) works in IDEA 2016.2.5.  @TSergey : Will you update the plugin?

**Comment by TSergey** [comment]
Fixed in 4.01 version
