### ISSUE TITLE
Can't get single line comment

### ISSUE THREAD

**Issue by ValerianSo** [setial/intellij-javadocs#57]
Hello,
I don't know if this is related to the plugin or to IntelliJ, but I'm trying to get single line comments for my bean fields.
Ie. like this:
/*\* The testField. */
private String testField;

And not like: 
/**
- The testField.
  */
  private String testField;

I'm using the following template (original one without '\n'):
/*\* <#if element.parent.isInterface()>The constant ${element.getName()}.<#else>The ${name}.</#if> */

Problem is that the template is not respected and I still get a multiline comment...

**Comment by TSergey** [comment]
To avoid multi line javadocs you need to change settings in your IDE:
Settings -> Edit*or -> Code Style -> Java
And check "Do not wrap one line comments".

![java_6ZPgpTcBB6](https://user-images.githubusercontent.com/1842437/76531683-4127b680-647e-11ea-8a6d-b4a05fccfeb0.png)
