### ISSUE TITLE
Java doc not generates for private methods

### ISSUE THREAD

**Issue by darwinfrancis** [setial/intellij-javadocs#59]
i have a function something like this
    private void saveCompanyName(String companyName) {
        preference.saveCompany(companyName)
    }

when i try to generate java doc nothing happens,but when i remove the private keyword the docs generated successfully.

gradle version : gradle:2.1.0
studio version : 2.1.1

**Comment by jmengelle** [comment]
There is an settings to enable javadoc generation for private method.

**Comment by darwinfrancis** [comment]
Okei, thank u

**Comment by vishal0910** [comment]
How to enable javadoc generation for private method.

**Comment by shanyuxiyun** [comment]
u can modify config file and add one line:
C:\Users\user\.IdeaIC2018.1\config\options\intellij-javadocs.xml

```
      <VISIBILITIES>
        <VISIBILITY>PUBLIC</VISIBILITY>
        <VISIBILITY>DEFAULT</VISIBILITY>
        <VISIBILITY>PROTECTED</VISIBILITY>
		<VISIBILITY>PRIVATE</VISIBILITY>
      </VISIBILITIES>
```

**Comment by EnjoyWall** [comment]
mac下的路径为 /Users/{username}/Library/Preferences/IntelliJIdea2019.1/options/intellij-javadocs.xml
