### ISSUE TITLE
Documentation needs more info on modifying templates

### ISSUE THREAD

**Issue by sdussin** [setial/intellij-javadocs#61]
I read the docs on the wiki about the template contents. What I can't seem to find is some sort of description saying where the templates can be found within the IDE.

A bit of a description showing where/how to access the templates to modify them would really help.

**Comment by mozhuwanjieDEV** [comment]
mark

**Comment by ranzou06** [comment]
check there.
https://github.com/setial/intellij-javadocs/issues/55

**Comment by TSergey** [comment]
Fixed in 4.01 version
