### ISSUE TITLE
 Can't find where to configure a Custom Java annotation template in idea-2016.1.1

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [setial/intellij-javadocs#62]
Can't find where to configure a Custom Java annotation template in idea-2016.1.1?

IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_05-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
javadoc-3.1.0

**Comment by ranzou06** [comment]
check there.
https://github.com/setial/intellij-javadocs/issues/55

**Comment by mozhuwanjieDEV** [comment]
@ranzou06  thank you very math !

**Comment by TSergey** [comment]
Fixed in 4.01 version
