### ISSUE TITLE
settings no config

### ISSUE THREAD

**Issue by tonycody** [setial/intellij-javadocs#65]
![qq 20160803151528](https://cloud.githubusercontent.com/assets/6773121/17357019/343d5286-598d-11e6-904c-0ca2870fe0f2.jpg)

**Comment by codeyuyu** [comment]
Me too!

**Comment by ranzou06** [comment]
check there.
#55

**Comment by ranzou06** [comment]
you can find the updated version [here](https://plugins.jetbrains.com/plugin/10163-javadoc2)

**Comment by TSergey** [comment]
Fixed in 4.01 version
