### ISSUE TITLE
How to edit the template?

### ISSUE THREAD

**Issue by zidoshare** [setial/intellij-javadocs#68]
I want to edit the template,but I don't know any key words like the live templates,${USER},${DATE},${TIME}...and more.

**Comment by shensmart** [comment]
me too, how to edit the template?
I am using 2016.3.2

**Comment by lizhecao** [comment]
I also want to know

**Comment by zhzhxtrrk** [comment]
if you can't see the config item in settings, you may be interested in my fork of this project, here is the URL: https://github.com/zhzhxtrrk/intellij-javadocs

**Comment by liangjiezhu** [comment]
use freemaker system variable？

**Comment by zhzhxtrrk** [comment]
@liangjiezhu in fact, it's VTL since this plugin uses velocity as it's template engine.

**Comment by TSergey** [comment]
Config window was fixed in 4.01 version
