### ISSUE TITLE
Cannot find settings on IDEA 2017.3

### ISSUE THREAD

**Issue by DesertCookie** [setial/intellij-javadocs#73]
It seems that the settings location somehow has changed... again.
I cannot find it anywhere and all the other issues talking about this are from 2016 and don't work...

**Comment by Ich5003** [comment]
I have the same problem, a fix would be nice.

**Comment by wmapps** [comment]
Take a look for **https://github.com/ranzou06/intellij-javadocs/blob/master/intellijPluginJavadoc.zip**

ranzou06 has fix it.

**Comment by ranzou06** [comment]
you can find the updated version [here](https://plugins.jetbrains.com/plugin/10163-javadoc2)
