### ISSUE TITLE
generate comments on private fields

### ISSUE THREAD

**Issue by CamiloMontoyaAdc** [setial/intellij-javadocs#82]
Is it possible to configure plugin in such a way that it will generate comments on private fields, methods, etc.?

**Comment by schittli** [comment]
**It's a great and very useful Plugin, thanks a lot!**

It looks like the only issue is the missing Doc for JavaDoc2:

I guess that JavaDoc2 is configured here in IntelliJ: `Settings » Other Settings » JavaDoc`
It this is true, then it should be mentioned in the Introduction Page. 

There, we can configure templates and enable the generator for private class items. 
It looks like the Plugin generates Comments if the `Visibiliy Private` is enabled.

**Comment by TSergey** [comment]
Fixed in 4.0.1 version

**Comment by schittli** [comment]
Thank you very much!
